# Generated by Django 4.2.4 on 2023-09-03 13:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='activity')),
            ],
            options={
                'verbose_name_plural': 'Activity',
            },
        ),
        migrations.CreateModel(
            name='ClientTestimonials',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('position', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='MainTestimonials')),
                ('content', models.TextField()),
            ],
            options={
                'verbose_name_plural': 'Client Testimonials',
            },
        ),
        migrations.CreateModel(
            name='ContactUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(max_length=12)),
                ('message', models.TextField()),
            ],
            options={
                'verbose_name_plural': 'Contact Us',
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_name', models.CharField(max_length=100)),
                ('event_description', models.TextField()),
                ('event_date', models.DateField()),
                ('event_payment', models.CharField(max_length=100)),
                ('event_specialities', models.CharField(max_length=100)),
                ('event_benefits', models.CharField(max_length=100)),
                ('event_quotes', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='GalleryPhotos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_category', models.CharField(max_length=100)),
                ('gallery_image', models.ImageField(upload_to='gallery_photos')),
            ],
            options={
                'verbose_name_plural': 'Gallery Photos',
            },
        ),
        migrations.CreateModel(
            name='LatestNews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('news_title', models.CharField(max_length=100)),
                ('news_date', models.DateField()),
                ('news_description', models.TextField()),
                ('new_image', models.ImageField(upload_to='New Imges/')),
            ],
            options={
                'verbose_name_plural': 'Latest News',
            },
        ),
        migrations.CreateModel(
            name='Packages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('package_name', models.CharField(max_length=100)),
                ('package_description', models.TextField()),
                ('package_image', models.ImageField(upload_to='Packages/')),
                ('package_slug', models.SlugField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Package',
            },
        ),
        migrations.CreateModel(
            name='Resort',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resort_name', models.CharField(max_length=100)),
                ('resort_description', models.TextField()),
                ('resort_service', models.CharField(max_length=100)),
                ('resort_aminities', models.CharField(max_length=100)),
                ('resort_amount', models.CharField(max_length=100)),
                ('resort_images', models.ImageField(upload_to='Resort_Image')),
                ('resort_slug', models.SlugField()),
                ('resort_package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.packages')),
            ],
            options={
                'verbose_name_plural': 'Resort',
            },
        ),
    ]
