# Generated by Django 4.2.4 on 2023-09-24 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='resort',
            old_name='resort_images',
            new_name='resort_image_1',
        ),
        migrations.AddField(
            model_name='resort',
            name='resort_image_2',
            field=models.ImageField(blank=True, null=True, upload_to='Resort_Image'),
        ),
        migrations.AddField(
            model_name='resort',
            name='resort_image_3',
            field=models.ImageField(blank=True, null=True, upload_to='Resort_Image'),
        ),
    ]
