# Generated by Django 4.2.4 on 2023-10-18 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='offer_percentage',
            field=models.CharField(max_length=10),
        ),
    ]
