# Generated by Django 4.2.4 on 2023-08-31 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LatestNews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('news_title', models.CharField(max_length=100)),
                ('news_date', models.DateField()),
                ('news_description', models.TextField()),
                ('new_image', models.ImageField(upload_to='New Imges/')),
            ],
        ),
    ]
