# Generated by Django 4.2.4 on 2023-08-31 13:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_latestnews'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='latestnews',
            options={'verbose_name_plural': 'Latest News'},
        ),
    ]
