# Generated by Django 4.2.4 on 2023-09-24 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_rename_resort_images_resort_resort_image_1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='resort',
            name='resort_image_4',
            field=models.ImageField(blank=True, null=True, upload_to='Resort_Image'),
        ),
        migrations.AddField(
            model_name='resort',
            name='resort_image_5',
            field=models.ImageField(blank=True, null=True, upload_to='Resort_Image'),
        ),
    ]
