# Generated by Django 4.2.1 on 2023-05-20 01:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_maintestimonials'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MainTestimonials',
            new_name='ClientTestimonials',
        ),
        migrations.AlterModelOptions(
            name='activity',
            options={'verbose_name_plural': 'Activity'},
        ),
        migrations.AlterModelOptions(
            name='clienttestimonials',
            options={'verbose_name_plural': 'Client Testimonials'},
        ),
    ]
