# Generated by Django 4.2.4 on 2023-10-08 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_resort_resort_image_4_resort_resort_image_5'),
    ]

    operations = [
        migrations.CreateModel(
            name='LatestEvents',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('news_title', models.CharField(max_length=100)),
                ('news_date', models.DateField()),
                ('news_description', models.TextField()),
                ('new_image', models.ImageField(upload_to='New Imges/')),
            ],
            options={
                'verbose_name_plural': 'Latest Events',
            },
        ),
        migrations.DeleteModel(
            name='LatestNews',
        ),
        migrations.AlterField(
            model_name='galleryphotos',
            name='gallery_image',
            field=models.ImageField(help_text='Upload only 740x493 pixels image', upload_to='gallery_photos'),
        ),
    ]
