# Generated by Django 4.2.4 on 2023-10-08 19:30

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_latestevents_delete_latestnews_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resort',
            name='id',
        ),
        migrations.AddField(
            model_name='resort',
            name='resort_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
