# Generated by Django 4.2.1 on 2023-05-26 10:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_contactus'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResortCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_package', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ResortName',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resort_name', models.CharField(max_length=100)),
                ('resort_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.resortcategory')),
            ],
        ),
    ]
