# Generated by Django 4.2.4 on 2023-10-09 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_remove_resort_id_resort_resort_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resort',
            name='resort_image_1',
            field=models.ImageField(blank=True, null=True, upload_to='Resort_Image'),
        ),
    ]
