# Generated by Django 4.2.4 on 2023-09-03 16:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('useradmin', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bestieadmin',
            name='resort_amount',
        ),
    ]
