# Generated by Django 4.2.4 on 2023-09-03 16:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_rename_resort_aminities_resort_resort_aminities_1_and_more'),
        ('useradmin', '0002_remove_bestieadmin_resort_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bestieadmin',
            name='resort_package',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.packages'),
        ),
        migrations.DeleteModel(
            name='BestiePackage',
        ),
    ]
