# Generated by Django 4.2.4 on 2023-09-16 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('useradmin', '0002_bestieadmin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bestieadmin',
            name='resort_slug',
            field=models.SlugField(blank=True, null=True),
        ),
    ]
